routes/web.php
<?php

use Illuminate\Support\Facades\Input;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| 
|
*/

//default route...


//for test mail
Route::get('/test', function()
{
	$beautymail = app()->make(Snowfire\Beautymail\Beautymail::class);
    $beautymail->send('email.welcome', [], function($message)
    {
        $message
			->from('kasunsevensigns@gmail.com')
			->to('roshanharshanadr@gmail.com', 'John Smith')
			->subject('Welcome!');
    });

});
//for end test mail




Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

//home routes...
Route::get('/home', 'HomeController@index')->name('home');

//back end routes...
Route::group(['middleware' => ['auth']], function(){
    
        Route::resource('admin','AdminController');
    
        //brand forms route...
        Route::resource('brand','BrandsController');
    
        //printer forms route...
        Route::resource('printer','PrintersController');
    
        //Product forms route...
        Route::resource('product','ProductsController');
    
        //Category forms route...
        Route::resource('category','CategoriesController');
    
        //Color forms route...
        Route::resource('color','ColorsController');
    
        //FAQ forms route...
        Route::resource('question','QuestionsController');

        //User forms route...
        Route::resource('user','QuestionsController');
    
        //Answer forms route...
        Route::resource('answer','AnswersController');
        Route::get('/answer/create/{question}','AnswersController@create');
        Route::get('/answer/{question}/{approve}','AnswersController@updateApprove');
        Route::delete('/question/delete/{question}', 'QuestionsController@destroyDashboard');
    
        //Diliveryrate forms route...
        Route::resource('diliveryrate','DeliveryratesController');
    
        //User register forms route...
        Route::resource('user','UsersController');
        Route::get('/user/change/privileges/{user}','UsersController@privileges');
        Route::post('/user/privileges/update','UsersController@updateprivileges');

        //for repors
        Route::get('/orderreport','ReportsController@orderreport');
        Route::get('/paymentreport','ReportsController@paymentreport');
        Route::get('/salesreport','ReportsController@salesreport');
        Route::get('/mail','ReportsController@mail');
        Route::post('/searchsales','ReportsController@searchsales')->name('searchsales');
        Route::get('/order/view/{orderId}','ReportsController@viewOrderDetails');

        Route::get('/searchsales', function () {

            return redirect('salesreport');

        });

});

//Aauth routes...
Route::resource('passwords','UseraccountController');

//model route...
Route::get('/model', 'ModelController@index');

//for search results...
Route::get('/search={search_id}','SearchController@index');
Route::get('/search/{brandId}/{search_id}/{catId}','SearchController@indexOther');
Route::get('/search={section}/{search_id}','SearchController@other');
Route::get('/toner-cartridges/{brandname}/{printername}/{printerId}.html','SearchController@tonerCartridgeShow');
Route::get('/ink-cartridges/{brandname}/{printername}/{printerId}.html','SearchController@inkCartridgeShow');
Route::get('/ribbon-cartridges/{brandname}/{printername}/{printerId}.html','SearchController@ribbonCartridgeShow');
Route::get('/bulk-ink/{brandname}/{printername}/{printerId}.html','SearchController@bulkinkCartridgeShow');
Route::get('/powder/{brandname}/{printername}/{printerId}.html','SearchController@powderCartridgeShow');
Route::get('/{printer_name}.html','SearchController@printerShow');

//for customer...
Route::get('/customer/view/{userId}','CustomerController@forviewOrders');

Route::get('/checkout/cart','Shopingcartscontroller@getCart');
Route::get('/add-to-cart/{id}/{UrlPast}/{count}/{stock}','Shopingcartscontroller@getAddToCart');
Route::get('/add-to-cart/product/{id}/{stock}/{count}/{UrlPast}','Shopingcartscontroller@getAddToCartonlyproduct');
// Route::get('/add-to-cart/{id}/{count}/{category}/{brand}/{printer}','Shopingcartscontroller@getAddToCartTwo');
Route::get('/add-to-cart/for-this-printer/{id}/{count}/printer/{stock}','Shopingcartscontroller@getAddToCartTwo');
Route::get('/change/product/{id}/{count}/{stock}/{side}','Shopingcartscontroller@getAddToCartChange');
Route::get('/contact','Shopingcartscontroller@contact');
Route::get('/city/{id}','Shopingcartscontroller@getcityDetails');

Route::get('/reduce/{id}','Shopingcartscontroller@getReduceByOne');
Route::get('/remove/{id}/{stock}/{count}','Shopingcartscontroller@getRemoveItem');
Route::get('/checkout','Shopingcartscontroller@getCheckout');
Route::get('/{category}/{brandname}.html','SearchController@getBrands');
//Route::post('/checkout','Shopingcartscontroller@postCheckout');
Route::post('/checkout',[
    'uses' => 'Shopingcartscontroller@postCheckout',
    'as' => 'checkout'
]);
Route::post('/checkemail',[
    'uses' => 'Shopingcartscontroller@checkemail',
    'as' => 'checkemail'
]);
Route::post('/delivery',[
    'uses' => 'Shopingcartscontroller@delivery',
    'as' => 'delivery'
]);
Route::any('/finished',[
    'uses' => 'Shopingcartscontroller@finished',
    'as' => 'finished'
]);

Route::any('/getapidetails','Shopingcartscontroller@getapidetails')->name('getapidetails');
Route::post('/getcashdetails','Shopingcartscontroller@getcashdetails')->name('getcashdetails');
Route::post('/customerQuestion', 'CustomerController@customerQuestion')->name('customerQuestion');
Route::post('/done', 'Shopingcartscontroller@done')->name('done');
Route::get('/checkemail', function () {

    return redirect('checkout');

});
Route::get('/delivery', function () {

    return redirect('delivery');

});

app/Http/Controllers/ProductsController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use App\Printer;
use App\ImageUp;
use App\Page;
use App\Category;
use App\Color;
use App\Brand;
use App\Feature;
use App\Attribute;
use App\Printer_Product;
use Image;
use Storage;
use Session;
use Auth;
use Redirect;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class ProductsController extends Controller
{
    /**
     * Controll user permissions...
     *
     * @return void
     */
    public function __construct()
    {
        if(Auth::user())
        {
            $sideRole = Auth::user()->role_id;
            $sidePermissions = DB::select('select * from permissions where role_id = ?', [$sideRole]);
            foreach ($sidePermissions as $sidePermission) {
                if ($sidePermission->name == 'Product') {
                    if ($sidePermission->index == 0) {
                        $this->middleware('guest', ['only' => ['index','show']]);
                    } elseif ($sidePermission->edit == 0) {
                        $this->middleware('guest', ['only' => ['edit','update']]);
                    }elseif ($sidePermission->create == 0) {
                        $this->middleware('guest', ['only' => ['create','store']]);
                    }elseif ($sidePermission->delete == 0) {
                        $this->middleware('guest', ['only' => ['destroy']]);
                    }     
                }
            }
        }
        else
        {
            $this->middleware('guest');
        }
    }
    
    /**
     * Display a listing of the product.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $printers = Printer::all();
        $products = Product::all();
        $features = Feature::all();
        return view('product.index',compact('printers','products','features'));
    }

    /**
     * Show the form for creating a new product.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $printer = Printer::all();
        $category = Category::all();
        $product = DB::table("products")->pluck("name","id");
        $color = DB::table("colors")->pluck("name","id");
        $brands = Brand::all();
        
        return view('product.create',compact('printer','category','product','color','brands'));
    }

    /**
     * Store a newly created product in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $product = Product::register($request);

        return $product;

    }

    /**
     * Display the specified product.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        //
    }

    /**
     * Show the form for editing the specified product.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        $editProduct = Product::editproduct($product);
        return $editProduct;
    }

    /**
     * Update the specified product in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $product = Product::updaterecord($request, $id);

        return $product;

    }

    /**
     * Remove the specified product from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {

        $findProduct = Product::deleterecord($product);
        return $findProduct;

    }
}

resources/views/product/index.blade.php
@extends('layouts.asset')
@section('content')

<div class="wrapper">

    @include('header')

    @include('sidemenu')
  
    <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Product
        <small>List</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Dashboard</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-xs-12">
          <div class="box">
            <div class="box-header">
              <h3 class="box-title">View Product List</h3>
            </div>

            @if (session('alert'))
                <div class="alert alert-success">
                    {{ session('alert') }}
                </div>
            @endif

            <?php
              $sideRole = auth()->user()->role_id;
              $sidePermissions = DB::select('select * from permissions where role_id = ?', [$sideRole]);
            ?>

          <div class="box-body">
            <table id="example2" class="table table-bordered table-hover">
              <thead>
              <tr>
                <th>#</th>
                <th>Name</th>
                <th>Category</th>
                <th>Image</th>
                <th>Price (Rs.)</th>
                <th>Vat (%)</th>
                <th>Printers</th>
                <th>Stock</th>
                <th>Features</th>
                <th>Edit</th>
                <th>Delete</th>
              </tr>
              </thead>
              <tbody>
                    <?php $i = 0; ?>
                  @foreach($products as $product)
                    <?php $i++ ?>
                  <tr>
                    <td>{{ $i }}</td>
                    <td>{{ $product->name }}</td>
                    <td>{{ $product->category->name }}</td>
                    <td><img src="{{ url('/') }}/image/{{ $product->image }}" width="250px" height="250px" /></td>
                    <td align="right">{{ number_format($product->price,2) }}</td>
                    <td>{{ $product->vat }}</td>
                    <td>
                      @foreach($product->printers as $printer)
                          {{ $printer->name }}<br>
                      @endforeach
                    </td>
                    <td>{{ $product->stock }}</td>
                    <td>
                      @foreach($product->features as $feature)
                          {{ $feature->name }}<br>
                      @endforeach
                    </td>
                    <td>
                      @foreach ($sidePermissions as $sidePermission)
                          @if ($sidePermission->name == 'Product')
                            @if ($sidePermission->edit == 1)
                              <a href="{{ url('/') }}/product/{{ $product->id }}/edit"><i class="fa fa-edit" style="font-size:25px; color:green"></i></a>
                            @else
                              <p style="color:red">No Access!!!</p>
                            @endif
                          @endif
                      @endforeach
                    </td>
                    <td>
                      @foreach ($sidePermissions as $sidePermission)
                          @if ($sidePermission->name == 'Product')
                            @if ($sidePermission->delete == 1)
                              <a href="#" onclick="
                              var result = confirm('Are you Delete this one!');
                                if( result )
                                {
                                    event.preventDefault();
                                    document.getElementById('delete-form{{ $product->id }}').submit();
                                }
                        "><i class="fa fa-trash-o" style="font-size:25px;color:red"></i></a>
                        
                                <form id="delete-form{{ $product->id }}" action="{{ route('product.destroy',[$product->id]) }}"
                                        method="POST" style="display: non;">
                                        <input type="hidden" name="_method" value="delete">
                                        {{ csrf_field() }}
                                </form>
                            @else
                              <p style="color:red">No Access!!!</p>
                            @endif
                          @endif
                      @endforeach
                    </td>
                  </tr>
                  @endforeach
              </tfoot>
            </table>
          </div>


        </div>
        <!-- /.box -->


      </div>
    </div>


    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
    @include('footer')
  
    @include('rightside')
    
    <div class="control-sidebar-bg"></div>
  </div>
  <!-- ./wrapper -->

@endsection