routes/web.php
<?php

use Illuminate\Support\Facades\Input;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| 
|
*/

//default route...


//for test mail
Route::get('/test', function()
{
	$beautymail = app()->make(Snowfire\Beautymail\Beautymail::class);
    $beautymail->send('email.welcome', [], function($message)
    {
        $message
			->from('kasunsevensigns@gmail.com')
			->to('roshanharshanadr@gmail.com', 'John Smith')
			->subject('Welcome!');
    });

});
//for end test mail




Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

//home routes...
Route::get('/home', 'HomeController@index')->name('home');

//back end routes...
Route::group(['middleware' => ['auth']], function(){
    
        Route::resource('admin','AdminController');
    
        //brand forms route...
        Route::resource('brand','BrandsController');
    
        //printer forms route...
        Route::resource('printer','PrintersController');
    
        //Product forms route...
        Route::resource('product','ProductsController');
    
        //Category forms route...
        Route::resource('category','CategoriesController');
    
        //Color forms route...
        Route::resource('color','ColorsController');
    
        //FAQ forms route...
        Route::resource('question','QuestionsController');

        //User forms route...
        Route::resource('user','QuestionsController');
    
        //Answer forms route...
        Route::resource('answer','AnswersController');
        Route::get('/answer/create/{question}','AnswersController@create');
        Route::get('/answer/{question}/{approve}','AnswersController@updateApprove');
        Route::delete('/question/delete/{question}', 'QuestionsController@destroyDashboard');
    
        //Diliveryrate forms route...
        Route::resource('diliveryrate','DeliveryratesController');
    
        //User register forms route...
        Route::resource('user','UsersController');
        Route::get('/user/change/privileges/{user}','UsersController@privileges');
        Route::post('/user/privileges/update','UsersController@updateprivileges');

        //for repors
        Route::get('/orderreport','ReportsController@orderreport');
        Route::get('/paymentreport','ReportsController@paymentreport');
        Route::get('/salesreport','ReportsController@salesreport');
        Route::get('/mail','ReportsController@mail');
        Route::post('/searchsales','ReportsController@searchsales')->name('searchsales');
        Route::get('/order/view/{orderId}','ReportsController@viewOrderDetails');

        Route::get('/searchsales', function () {

            return redirect('salesreport');

        });

});

//Aauth routes...
Route::resource('passwords','UseraccountController');

//model route...
Route::get('/model', 'ModelController@index');

//for search results...
Route::get('/search={search_id}','SearchController@index');
Route::get('/search/{brandId}/{search_id}/{catId}','SearchController@indexOther');
Route::get('/search={section}/{search_id}','SearchController@other');
Route::get('/toner-cartridges/{brandname}/{printername}/{printerId}.html','SearchController@tonerCartridgeShow');
Route::get('/ink-cartridges/{brandname}/{printername}/{printerId}.html','SearchController@inkCartridgeShow');
Route::get('/ribbon-cartridges/{brandname}/{printername}/{printerId}.html','SearchController@ribbonCartridgeShow');
Route::get('/bulk-ink/{brandname}/{printername}/{printerId}.html','SearchController@bulkinkCartridgeShow');
Route::get('/powder/{brandname}/{printername}/{printerId}.html','SearchController@powderCartridgeShow');
Route::get('/{printer_name}.html','SearchController@printerShow');

//for customer...
Route::get('/customer/view/{userId}','CustomerController@forviewOrders');

Route::get('/checkout/cart','Shopingcartscontroller@getCart');
Route::get('/add-to-cart/{id}/{UrlPast}/{count}/{stock}','Shopingcartscontroller@getAddToCart');
Route::get('/add-to-cart/product/{id}/{stock}/{count}/{UrlPast}','Shopingcartscontroller@getAddToCartonlyproduct');
// Route::get('/add-to-cart/{id}/{count}/{category}/{brand}/{printer}','Shopingcartscontroller@getAddToCartTwo');
Route::get('/add-to-cart/for-this-printer/{id}/{count}/printer/{stock}','Shopingcartscontroller@getAddToCartTwo');
Route::get('/change/product/{id}/{count}/{stock}/{side}','Shopingcartscontroller@getAddToCartChange');
Route::get('/contact','Shopingcartscontroller@contact');
Route::get('/city/{id}','Shopingcartscontroller@getcityDetails');

Route::get('/reduce/{id}','Shopingcartscontroller@getReduceByOne');
Route::get('/remove/{id}/{stock}/{count}','Shopingcartscontroller@getRemoveItem');
Route::get('/checkout','Shopingcartscontroller@getCheckout');
Route::get('/{category}/{brandname}.html','SearchController@getBrands');
//Route::post('/checkout','Shopingcartscontroller@postCheckout');
Route::post('/checkout',[
    'uses' => 'Shopingcartscontroller@postCheckout',
    'as' => 'checkout'
]);
Route::post('/checkemail',[
    'uses' => 'Shopingcartscontroller@checkemail',
    'as' => 'checkemail'
]);
Route::post('/delivery',[
    'uses' => 'Shopingcartscontroller@delivery',
    'as' => 'delivery'
]);
Route::any('/finished',[
    'uses' => 'Shopingcartscontroller@finished',
    'as' => 'finished'
]);

Route::any('/getapidetails','Shopingcartscontroller@getapidetails')->name('getapidetails');
Route::post('/getcashdetails','Shopingcartscontroller@getcashdetails')->name('getcashdetails');
Route::post('/customerQuestion', 'CustomerController@customerQuestion')->name('customerQuestion');
Route::post('/done', 'Shopingcartscontroller@done')->name('done');
Route::get('/checkemail', function () {

    return redirect('checkout');

});
Route::get('/delivery', function () {

    return redirect('delivery');

});

app/Brand.php
<?php

namespace App;

use App\Classes\ImageUpload;
use Illuminate\Database\Eloquent\Model;
use Storage;
use App\ImageUp;

class Brand extends Model
{
   
    protected $fillable = [
        'name',
        'description',
        'image',
    ];

    // relations

    public function printers()
    {
        return $this->hasMany('App\Printer');
    }
    public function products()
    {
        return $this->hasMany('App\Product');
    }

    // end relations

    /**
     * Store a newly created Brand in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response $post
     */
    public static function register($request){

        $image = $request->file('image');

        $imagesize = ImageUpload::checkSize($image);
        $imagetype = ImageUpload::checkType($image);
        //dd($imagetype);

        if($imagesize == 'yes' && $imagetype == 'yes')
        {
            $post = new Brand;
            $post->name = $request->input('brandname');
            $post->description = $request->input('description');

            $width = 250;
            $height = 200;

            if ($request->hasfile('image'))
            {
                //$image = $request->file('image');

                $imageupload = ImageUpload::uploadImage($image,$width,$height);
                $post->image = $imageupload;

            }

            $post->save();

            if ($request->hasfile('image'))
            {
                //$image = $request->file('image');

                $imageupload = ImageUpload::uploadImage($image,$width,$height);

                // get extention
                $ext = pathinfo(storage_path().$imageupload, PATHINFO_EXTENSION);

                $post = new ImageUp;
                $post->name = $imageupload;
                $post->alt = '';
                $post->type = $ext;
                $post->save();
            }

            //return $post;
            if($post)
            {
                return redirect()->back()->with('alert', 'Success!');
            }
            else
            {
                return redirect()->back()->with('alert2', 'Not Success!');
            }

        }
        else
        {
            return redirect()->back()->with('alert2', 'Unsupported image type or size! It must be lower 2Mb and type is jpg, jpeg, or png!');
        }

    }

    /**
     * Update the specified Brand in storage.
     *
     * @param  \Illuminate\Http\Request  $request, $id
     * @return \Illuminate\Http\Response 
     */
    public static function updaterecord($request, $id){

        $image = $request->file('image');

            $post = Brand::find($id);
            $post->name = $request->input('brandname');
            $post->description = $request->input('description');

            $width = 250;
            $height = 200;

            if ($request->hasfile('image'))
            {
                //$image = $request->file('image');

                $imageupload = ImageUpload::uploadImage($image,$width,$height);
                $post->image = $imageupload;

                $oldfilename = $post->image;

                $post->image =  $imageupload;

                Storage::delete($oldfilename);
            }
            $post->save();

            //save image details for image_ups table
            if ($request->hasfile('image'))
            {
                //$image = $request->file('image');

                $imageupload = ImageUpload::uploadImage($image,$width,$height);

                // get extention
                $ext = pathinfo(storage_path().$imageupload, PATHINFO_EXTENSION);

                $post = new ImageUp;
                $post->name = $imageupload;
                $post->alt = '';
                $post->type = $ext;
                $post->save();
            }

            $brandNew = Brand::all();
            return view('brand.index',['brand'=> $brandNew]);

    }

    /**
     * Remove the specified brand in storage.
     *
     * @param  \Illuminate\Http\Request  $brand
     * @return \Illuminate\Http\Response $brandNew
     */
    public static function deleterecord($brand){

        $brand = Brand::find( $brand->id );
        $brandNew = $brand->delete();

        return $brandNew;

    }
    
}

app/Http/Controllers/BrandsController.php
<?php

namespace App\Http\Controllers;

use App\Brand;
use App\ImageUp;
use App\Classes\ImageUpload;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use View;
use Image;
use Storage;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;
use Session;
use Redirect;

class BrandsController extends Controller
{
    /**
     * Controll user permissions...
     *
     * @return void
     */
    public function __construct()
    {
        if(Auth::user())
        {
            $sideRole = Auth::user()->role_id;
            $sidePermissions = DB::select('select * from permissions where role_id = ?', [$sideRole]);
            foreach ($sidePermissions as $sidePermission) {
                if ($sidePermission->name == 'Brand') {
                    if ($sidePermission->index == 0) {
                        $this->middleware('guest', ['only' => ['index','show']]);
                    } elseif ($sidePermission->edit == 0) {
                        $this->middleware('guest', ['only' => ['edit','update']]);
                    }elseif ($sidePermission->create == 0) {
                        $this->middleware('guest', ['only' => ['create','store']]);
                    }elseif ($sidePermission->delete == 0) {
                        $this->middleware('guest', ['only' => ['destroy']]);
                    }     
                }
            }
        }
        else
        {
            $this->middleware('guest');
        }
    }

    /**
     * Display a listing of the brand.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $brand = Brand::all();
        return view('brand.index',['brand'=> $brand]);

    }

    /**
     * Show the form for creating a new brand.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('brand.create');
    }

    /**
     * Store a newly created brand in storage.
     *
     * @param  \Illuminate\Http\Request  $brand
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

            $brand = Brand::register($request);
    
            return $brand;
        
    }

    /**
     * Display the specified brand.
     *
     * @param  \App\Brand  $brand
     * @return \Illuminate\Http\Response
     */
    public function show(Brand $brand)
    {
        //
    }

    /**
     * Show the form for editing the specified brand.
     *
     * @param  \App\Brand  $brand
     * @return \Illuminate\Http\Response
     */
    public function edit(Brand $brand)
    {
        $brand = Brand::find( $brand->id );
        return view('brand.edit',['brand'=>$brand]);
    }

    /**
     * Update the specified brand in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Brand  $brand
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $brand = Brand::updaterecord($request, $id);
        
        return $brand;
    }

    /**
     * Remove the specified brand from storage.
     *
     * @param  \App\Brand  $findBrand,$brand
     * @return \Illuminate\Http\Response
     */
    public function destroy(Brand $brand)
    {
        
        $findBrand = Brand::deleterecord($brand);
        if($findBrand) {

            return redirect('brand')->with('alert', 'Deleted!');
        }

            return redirect('brand')->with('alert2','Brand could not be deleted!');
    }
}

resources/views/brand/create.blade.php
@extends('layouts.asset')
@section('content')

<div class="wrapper">

    @include('header')

    @include('sidemenu')
  
    <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Add
        <small>Brand</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Dashboard</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <!-- Small boxes (Stat box) -->
      <div class="row">
            <div class="col-md-6">
              <!-- general form elements -->
              <div class="box box-primary">
                <div class="box-header with-border">
                  <h3 class="box-title">Add new Brand</h3>
                </div>
                
                @if (session('alert'))
                    <div class="alert alert-success">
                        {{ session('alert') }}
                    </div>
                @endif

                @if (session('alert2'))
                    <div class="alert alert-danger">
                        {{ session('alert2') }}
                    </div>
                @endif

                <form id="brandformstore" method="post" action="{{ route('brand.store') }}" enctype="multipart/form-data">
                {{ csrf_field() }}
                  <div class="box-body">
                    <div class="form-group col-md-12">
                      <label for="brandnamee" control-label>Brand Name</label>
                      <input type="text" name='brandname' class="form-control" id="brandname" required placeholder="Enter brand name!">
                    </div>
                    <div class="form-group col-md-12">
                      <label for="brandsimage">File input</label>
                      <input type="file" id="image" name="image" size="1MB" required />
                      <p class="help-block">Upload printer image!</p>
                    </div>
                    <div class="form-group col-md-12">
                      <label for="description" control-label>Description</label>
                      <textarea class="form-control" rows="5" name="description" id="description" placeholder="Enter description..." required></textarea>
                    </div>
                  </div>

                  <div class="box-footer">
                    <button id='submit' type="submit" class="btn btn-primary">Submit</button>
                  </div>
                </form>
              </div>


          </div>
          
    </div>

    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
    @include('footer')
  
    @include('rightside')
    
    <div class="control-sidebar-bg"></div>
  </div>
  <!-- ./wrapper -->

 


@endsection

resources/views/brand/edit.blade.php
@extends('layouts.asset')
@section('content')

<div class="wrapper">

    @include('header')

    @include('sidemenu')
  
    <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Add
        <small>Brand</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Dashboard</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <!-- Small boxes (Stat box) -->
      <div class="row">
            <div class="col-md-6">
              <!-- general form elements -->
              <div class="box box-primary">
                <div class="box-header with-border">
                  <h3 class="box-title">Add new Brand</h3>
                </div>
                
                @if (session('alert'))
                    <div class="alert alert-success">
                        {{ session('alert') }}
                    </div>
                @endif
                
                @if (session('alert2'))
                    <div class="alert alert-danger">
                        {{ session('alert2') }}
                    </div>
                @endif

                {{ Form::model($brand, array('route' => array('brand.update', $brand->id), 'method' => 'PUT', 'files' => true)) }}

                  <div class="box-body">

                    <div class="form-group col-md-12">
                      <label for="brandnamee" control-label>Brand Name</label>
                      <input type="text" name='brandname' class="form-control" id="brandname" value="{{ $brand->name }}" required placeholder="Enter brand name!">
                    </div>

                    <div class="form-group col-md-6">
                      <label for="brandsimage">File input</label>
                      <input type="file" id="image" name="image" />
                      <p class="help-block">Upload printer image!</p>
                    </div>

                    <div class="form-group col-md-6">
                      <img src="{{ url('/') }}/image/{{ $brand->image }}" width="200px" height="150px" />
                    </div>

                    <div class="form-group col-md-12">
                      <label for="description" control-label>Description</label>
                      <textarea class="form-control" rows="5" name="description" id="description" placeholder="Enter feacher..." required>{{ $brand->description }}</textarea>
                    </div>

                  </div>

                  <div class="box-footer">
                    <button id='submit' type="submit" class="btn btn-primary">Submit</button>
                  </div>
                {{ Form::close() }}
              </div>


          </div>
          
    </div>

    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
    @include('footer')
  
    @include('rightside')
    
    <div class="control-sidebar-bg"></div>
  </div>
  <!-- ./wrapper -->

 


@endsection

resources/views/brand/index.blade.php
@extends('layouts.asset')
@section('content')

<div class="wrapper">

    @include('header')

    @include('sidemenu')
  
    <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Brands
        <small>List</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Dashboard</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-xs-12">
          <div class="box">
            <div class="box-header">
              <h3 class="box-title">View Brands List</h3>
            </div>

            @if (session('alert'))
                <div class="alert alert-success">
                    {{ session('alert') }}
                </div>
            @endif
            @if (session('alert2'))
                  <div class="alert alert-danger">
                      {{ session('alert2') }}
                  </div>
              @endif

            <?php
              $sideRole = auth()->user()->role_id;
              $sidePermissions = DB::select('select * from permissions where role_id = ?', [$sideRole]);
            ?>

          <div class="box-body">
            <table id="example2" class="table table-bordered table-hover">
              <thead>
              <tr>
                <th>#</th>
                <th>Name</th>
                <th>Description</th>
                <th>Image</th>
                <th>Edit</th>
                <th>Delete</th>                
              </tr>
              </thead>
              <tbody>
                  <?php $i = 0; ?>
              @foreach($brand as $brand)
                  <?php $i++ ?>
              <tr>
                <td>{{ $i }}</td>
                <td>{{ $brand->name }}</td>
                <td>{{ $brand->description }}</td>
                <td><img src="{{ url('/') }}/image/{{ $brand->image }}" width="250px" height="150px" /></td>
                <td>
                    @foreach ($sidePermissions as $sidePermission)
                        @if ($sidePermission->name == 'Brand')
                          @if ($sidePermission->edit == 1)
                            <a href="{{ url('/') }}/brand/{{ $brand->id }}/edit"><i class="fa fa-edit" style="font-size:25px;  color:green"></i></a>
                          @else
                            <p style="color:red">No Access!!!</p>
                          @endif
                        @endif
                    @endforeach
                </td>
                <td>
                  @foreach ($sidePermissions as $sidePermission)
                      @if ($sidePermission->name == 'Brand')
                        @if ($sidePermission->delete == 1)
                        <a href="#" onclick="
                        var result = confirm('Are you Delete this one!');
                          if( result )
                          {
                              event.preventDefault();
                              document.getElementById('delete-form{{ $brand->id }}').submit();
                          }
                  "><i class="fa fa-trash-o" style="font-size:25px;color:red"></i></a>
                  
                          <form id="delete-form{{ $brand->id }}" action="{{ route('brand.destroy',[$brand->id]) }}"
                                  method="POST" style="display: non;">
                                  <input type="hidden" name="_method" value="delete">
                                  {{ csrf_field() }}
                          </form>
                        @else
                          <p style="color:red">No Access!!!</p>
                        @endif
                      @endif
                  @endforeach
                </td>
                        
              </tr>
              @endforeach
              
              </tfoot>
            </table>
                        
          </div>


        </div>
        <!-- /.box -->


      </div>
    </div>


    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
    @include('footer')
  
    @include('rightside')
    
    <div class="control-sidebar-bg"></div>
  </div>
  <!-- ./wrapper -->

@endsection