routes/web.php
<?php

use Illuminate\Support\Facades\Input;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| 
|
*/

//default route...


//for test mail
Route::get('/test', function()
{
	$beautymail = app()->make(Snowfire\Beautymail\Beautymail::class);
    $beautymail->send('email.welcome', [], function($message)
    {
        $message
			->from('kasunsevensigns@gmail.com')
			->to('roshanharshanadr@gmail.com', 'John Smith')
			->subject('Welcome!');
    });

});
//for end test mail




Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

//home routes...
Route::get('/home', 'HomeController@index')->name('home');

//back end routes...
Route::group(['middleware' => ['auth']], function(){
    
        Route::resource('admin','AdminController');
    
        //brand forms route...
        Route::resource('brand','BrandsController');
    
        //printer forms route...
        Route::resource('printer','PrintersController');
    
        //Product forms route...
        Route::resource('product','ProductsController');
    
        //Category forms route...
        Route::resource('category','CategoriesController');
    
        //Color forms route...
        Route::resource('color','ColorsController');
    
        //FAQ forms route...
        Route::resource('question','QuestionsController');

        //User forms route...
        Route::resource('user','QuestionsController');
    
        //Answer forms route...
        Route::resource('answer','AnswersController');
        Route::get('/answer/create/{question}','AnswersController@create');
        Route::get('/answer/{question}/{approve}','AnswersController@updateApprove');
        Route::delete('/question/delete/{question}', 'QuestionsController@destroyDashboard');
    
        //Diliveryrate forms route...
        Route::resource('diliveryrate','DeliveryratesController');
    
        //User register forms route...
        Route::resource('user','UsersController');
        Route::get('/user/change/privileges/{user}','UsersController@privileges');
        Route::post('/user/privileges/update','UsersController@updateprivileges');

        //for repors
        Route::get('/orderreport','ReportsController@orderreport');
        Route::get('/paymentreport','ReportsController@paymentreport');
        Route::get('/salesreport','ReportsController@salesreport');
        Route::get('/mail','ReportsController@mail');
        Route::post('/searchsales','ReportsController@searchsales')->name('searchsales');
        Route::get('/order/view/{orderId}','ReportsController@viewOrderDetails');

        Route::get('/searchsales', function () {

            return redirect('salesreport');

        });

});

//Aauth routes...
Route::resource('passwords','UseraccountController');

//model route...
Route::get('/model', 'ModelController@index');

//for search results...
Route::get('/search={search_id}','SearchController@index');
Route::get('/search/{brandId}/{search_id}/{catId}','SearchController@indexOther');
Route::get('/search={section}/{search_id}','SearchController@other');
Route::get('/toner-cartridges/{brandname}/{printername}/{printerId}.html','SearchController@tonerCartridgeShow');
Route::get('/ink-cartridges/{brandname}/{printername}/{printerId}.html','SearchController@inkCartridgeShow');
Route::get('/ribbon-cartridges/{brandname}/{printername}/{printerId}.html','SearchController@ribbonCartridgeShow');
Route::get('/bulk-ink/{brandname}/{printername}/{printerId}.html','SearchController@bulkinkCartridgeShow');
Route::get('/powder/{brandname}/{printername}/{printerId}.html','SearchController@powderCartridgeShow');
Route::get('/{printer_name}.html','SearchController@printerShow');

//for customer...
Route::get('/customer/view/{userId}','CustomerController@forviewOrders');

Route::get('/checkout/cart','Shopingcartscontroller@getCart');
Route::get('/add-to-cart/{id}/{UrlPast}/{count}/{stock}','Shopingcartscontroller@getAddToCart');
Route::get('/add-to-cart/product/{id}/{stock}/{count}/{UrlPast}','Shopingcartscontroller@getAddToCartonlyproduct');
// Route::get('/add-to-cart/{id}/{count}/{category}/{brand}/{printer}','Shopingcartscontroller@getAddToCartTwo');
Route::get('/add-to-cart/for-this-printer/{id}/{count}/printer/{stock}','Shopingcartscontroller@getAddToCartTwo');
Route::get('/change/product/{id}/{count}/{stock}/{side}','Shopingcartscontroller@getAddToCartChange');
Route::get('/contact','Shopingcartscontroller@contact');
Route::get('/city/{id}','Shopingcartscontroller@getcityDetails');

Route::get('/reduce/{id}','Shopingcartscontroller@getReduceByOne');
Route::get('/remove/{id}/{stock}/{count}','Shopingcartscontroller@getRemoveItem');
Route::get('/checkout','Shopingcartscontroller@getCheckout');
Route::get('/{category}/{brandname}.html','SearchController@getBrands');
//Route::post('/checkout','Shopingcartscontroller@postCheckout');
Route::post('/checkout',[
    'uses' => 'Shopingcartscontroller@postCheckout',
    'as' => 'checkout'
]);
Route::post('/checkemail',[
    'uses' => 'Shopingcartscontroller@checkemail',
    'as' => 'checkemail'
]);
Route::post('/delivery',[
    'uses' => 'Shopingcartscontroller@delivery',
    'as' => 'delivery'
]);
Route::any('/finished',[
    'uses' => 'Shopingcartscontroller@finished',
    'as' => 'finished'
]);

Route::any('/getapidetails','Shopingcartscontroller@getapidetails')->name('getapidetails');
Route::post('/getcashdetails','Shopingcartscontroller@getcashdetails')->name('getcashdetails');
Route::post('/customerQuestion', 'CustomerController@customerQuestion')->name('customerQuestion');
Route::post('/done', 'Shopingcartscontroller@done')->name('done');
Route::get('/checkemail', function () {

    return redirect('checkout');

});
Route::get('/delivery', function () {

    return redirect('delivery');

});

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Permission;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\DB;
use Session;
use Auth;
use Redirect;

class UsersController extends Controller
{
    /**
     * Controll user permissions...
     *
     * @return void
     */
    public function __construct()
    {
        if(Auth::user())
        {
            $sideRole = Auth::user()->role_id;
            $sidePermissions = DB::select('select * from permissions where role_id = ?', [$sideRole]);
            foreach ($sidePermissions as $sidePermission) {
                if ($sidePermission->name == 'User') {
                    if ($sidePermission->index == 0) {
                        $this->middleware('guest', ['only' => ['index','show','privileges']]);
                    } elseif ($sidePermission->edit == 0) {
                        $this->middleware('guest', ['only' => ['edit','update','updateprivileges']]);
                    }elseif ($sidePermission->create == 0) {
                        $this->middleware('guest', ['only' => ['create','store']]);
                    }elseif ($sidePermission->delete == 0) {
                        $this->middleware('guest', ['only' => ['destroy']]);
                    }     
                }
            }
        }
        else
        {
            $this->middleware('guest');
        }
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = User::all();
        return view('user.index',['user'=>$user]);
    }

    /**
     * Display all users.
     *
     * @param  \Illuminate\Http\Request  $user
     * @return \Illuminate\Http\Response
     */
    public function privileges($user)
    {
        $userRole = $user;
        $priview = Permission::where('role_id', $user)->get();
        return view('user.show',['priview'=>$priview],['userRole'=>$userRole]);
        
    }

    /**
     * Display all users.
     *
     * @param  \Illuminate\Http\Request  $role
     * @return \Illuminate\Http\Response
     */
    public function updateprivileges(Request $request)
    {

        $user = User::updateprivilegesNew($request);
        return $user;

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $user = User::register($request);
        return $user;

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $user = User::find( $user->id );
        return view('user.edit',['user'=>$user]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $printer = User::updaterecord($request, $id);

        $user = User::all();
        return view('user.index',['user'=>$user]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user = User::deleterecord($user);
        return $user;
    }
}

resources/views/user/create.blade.php
@extends('layouts.asset')
@section('content')

<div class="wrapper">

    @include('header')

    @include('sidemenu')
  
    <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Add
        <small>Users</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Dashboard</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <!-- Small boxes (Stat box) -->
      <div class="row">
            <div class="col-md-6">
              <!-- general form elements -->
              <div class="box box-primary">
                <div class="box-header with-border">
                  <h3 class="box-title">Add Users</h3>
                </div>
                
                @if (session('alert'))
                    <div class="alert alert-success">
                        {{ session('alert') }}
                    </div>
                @endif

                @if (session('alert2'))
                    <div class="alert alert-success">
                        {{ session('alert') }}
                    </div>
                @endif

                    <form method="POST" action="{{ route('user.store') }}">
                    {{ csrf_field() }}
                    <div class="box-body">
                    <div class="form-group col-md-8">
                        <input id="name" type="text" class="form-control" name="name" value="{{ old('name') }}" required autofocus placeholder="Name">

                                @if ($errors->has('name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                    </div>
                    <div class="form-group col-md-8">

                        <input id="email" type="email" class="form-control" name="email" value="{{ old('email') }}" required placeholder="Email">

                                @if ($errors->has('email'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                @endif
                    </div>
                    <div class="form-group col-md-8">

                        <input id="password" type="password" class="form-control" name="password" required placeholder="Password">

                                @if ($errors->has('password'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                                @endif
                    </div>
                    <div class="form-group col-md-8">

                        <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required placeholder="Retype password">

                    </div>

                    <div class="form-group col-md-8">
                        <select class="form-control" id="role" name="role" required>
                            <option>--select role--</option>
                            <option value="1">Admin</option>
                            <option value="2">User</option>
                          </select>

                                @if ($errors->has('role'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('role') }}</strong>
                                    </span>
                                @endif
                    </div>

                    <div class="row">
                        <div class="col-xs-6">
                            
                        </div>
                        <div class="col-xs-2">
                            <button type="submit" class="btn btn-primary">Register</button>
                        </div>
                        <!-- /.col -->
                        <div class="col-xs-4">
                        
                        </div>
                        <!-- /.col -->
                    </div>
                </div>
                    </form>
    
                </div>


            </div>
            
      </div>
  
      </section>
      <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
      @include('footer')
    
      @include('rightside')
      
      <div class="control-sidebar-bg"></div>
    </div>
    <!-- ./wrapper -->
  
   
  
  
  @endsection

resources/views/user/edit.blade.php
@extends('layouts.asset')
@section('content')

<div class="wrapper">

    @include('header')

    @include('sidemenu')
  
    <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Edit
        <small>User</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Dashboard</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <!-- Small boxes (Stat box) -->
      <div class="row">
            <div class="col-md-6">
              <!-- general form elements -->
              <div class="box box-primary">
                <div class="box-header with-border">
                  <h3 class="box-title">Edit User</h3>
                </div>
                
                @if (session('alert'))
                    <div class="alert alert-success">
                        {{ session('alert') }}
                    </div>
                @endif
                @if (session('alert2'))
                    <div class="alert alert-success">
                        {{ session('alert') }}
                    </div>
                @endif

                {{ Form::model($user, array('route' => array('user.update', $user->id), 'method' => 'PUT', 'files' => true)) }}

                  <div class="box-body">
                    <div class="form-group col-md-8">
                      <input id="name" type="text" class="form-control" name="name" value="{{ $user->name }}" required autofocus placeholder="Name">

                              @if ($errors->has('name'))
                                  <span class="help-block">
                                      <strong>{{ $errors->first('name') }}</strong>
                                  </span>
                              @endif
                  </div>
                  <div class="form-group col-md-8">

                      <input id="email" type="email" class="form-control" name="email" value="{{ $user->email }}" required placeholder="Email">

                              @if ($errors->has('email'))
                                  <span class="help-block">
                                      <strong>{{ $errors->first('email') }}</strong>
                                  </span>
                              @endif
                  </div>
                  <div class="form-group col-md-8">
                      <select class="form-control" id="role" name="role" required>
                          <option value="{{ $user->role_id }}">{{ $user->role->name }}</option>
                          <option value="1">Admin</option>
                          <option value="2">User</option>
                        </select>

                              @if ($errors->has('role'))
                                  <span class="help-block">
                                      <strong>{{ $errors->first('role') }}</strong>
                                  </span>
                              @endif
                  </div>
                  </div>

                  <div class="box-footer">
                    <div class="col-xs-6">
                            
                    </div>
                    <div class="col-xs-2">
                      <button id='submit' type="submit" class="btn btn-primary">Submit</button>
                    </div>
                    <!-- /.col -->
                    <div class="col-xs-4">
                    
                    </div>
                    <!-- /.col -->
                  </div>
                  {{ Form::close() }}
              </div>


          </div>
          
    </div>

    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
    @include('footer')
  
    @include('rightside')
    
    <div class="control-sidebar-bg"></div>
  </div>
  <!-- ./wrapper -->

 


@endsection

resources/views/user/index.blade.php
@extends('layouts.asset')
@section('content')

<div class="wrapper">

    @include('header')

    @include('sidemenu')
  
    <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Users
        <small>List</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Dashboard</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-xs-12">
          <div class="box">
            <div class="box-header">
              <h3 class="box-title">View Users List</h3>
            </div>

            @if (session('alert'))
                <div class="alert alert-success">
                    {{ session('alert') }}
                </div>
            @endif

            @if (session('alert2'))
                <div class="alert alert-danger">
                    {{ session('alert') }}
                </div>
            @endif

            <?php
              $sideRole = auth()->user()->role_id;
              $sidePermissions = DB::select('select * from permissions where role_id = ?', [$sideRole]);
            ?>

          <div class="box-body">
            <table id="example2" class="table table-bordered table-hover">
              <thead>
              <tr>
                <th>#</th>
                <th>Name</th>
                <th>E-mail</th>
                <th>Role</th>
                <th>Edit</th>
                <th>Delete</th>                
              </tr>
              </thead>
              <tbody>
                  <?php $i = 0; ?>
              @foreach($user as $user)
              @if($user->id != 1)
              <?php $i++ ?>
              <tr>
                <td>{{ $i }}</td>
                <td>{{ $user->name }}</td>
                <td>{{ $user->email }}</td>
                <td>{{ $user->role->name }}</td>
                <td>
                  @foreach ($sidePermissions as $sidePermission)
                      @if ($sidePermission->name == 'User')
                        @if ($sidePermission->edit == 1)
                          <a href="{{ url('/') }}/user/{{ $user->id }}/edit"><i class="fa fa-edit" style="font-size:25px;  question:green"></i></a>
                        @else
                          <p style="color:red">No Access!!!</p>
                        @endif
                      @endif
                  @endforeach
                </td>
                <td>
                  @foreach ($sidePermissions as $sidePermission)
                      @if ($sidePermission->name == 'User')
                        @if ($sidePermission->delete == 1)
                          <a href="#" onclick="
                          var result = confirm('Are you Delete this one!');
                            if( result )
                            {
                                event.preventDefault();
                                document.getElementById('delete-form{{ $user->id }}').submit();
                            }
                    "><i class="fa fa-trash-o" style="font-size:25px;color:red"></i></a>
                    
                            <form id="delete-form{{ $user->id }}" action="{{ route('user.destroy',[$user->id]) }}"
                                    method="POST" style="display: non;">
                                    <input type="hidden" name="_method" value="delete">
                                    {{ csrf_field() }}
                            </form>
                        @else
                          <p style="color:red">No Access!!!</p>
                        @endif
                      @endif
                  @endforeach
                </td>
                        
              </tr>
              @endif
              @endforeach
              
              </tfoot>
            </table>
                 
            
            <div class="form-group col-md-12">
                <div class="form-group col-md-2">

                  @foreach ($sidePermissions as $sidePermission)
                      @if ($sidePermission->name == 'User')
                        @if ($sidePermission->edit == 1)

                        <p style="font-size: 16px; color: red; border: 1px solid green; border-radius: 3px; padding:5px"><b><a href="{{ url('/') }}/user/change/privileges/1"> <i class="fa fa-pencil" style="font-size:25px;  question:blue"></i></a> Change Admin Privileges</b></p>

                        <p style="font-size: 16px; color: red; border: 1px solid green; border-radius: 3px; padding:5px"><b><a href="{{ url('/') }}/user/change/privileges/2"><i class="fa fa-pencil" style="font-size:25px;  question:blue"></i></a> Change User Privileges</b></p>
                        
                        @endif
                      @endif
                  @endforeach

                </div>
                <div class="form-group col-md-10">
                  
                </div>
            </div>


          </div>


        </div>
        <!-- /.box -->


      </div>
    </div>


    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
    @include('footer')
  
    @include('rightside')
    
    <div class="control-sidebar-bg"></div>
  </div>
  <!-- ./wrapper -->

@endsection

resources/views/user/show.blade.php
@extends('layouts.asset')
@section('content')

<div class="wrapper">

    @include('header')

    @include('sidemenu')
  
    <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Users
        <small>Privileges</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Dashboard</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-xs-12">
          <div class="box">
            <div class="box-header">
              <h3 class="box-title">View Privileges</h3>
            </div>

            @if (session('alert'))
                <div class="alert alert-success">
                    {{ session('alert') }}
                </div>
            @endif

            @if (session('alert2'))
                <div class="alert alert-danger">
                    {{ session('alert') }}
                </div>
            @endif

            <form method="POST" action="{{action('UsersController@updateprivileges')}}">
              {{ csrf_field() }}

            <input type="hidden" name="userRole" id="userRole" value="{{ $userRole }}">
            <label for="brandsimage" style="padding-left:10px; font-size: 16px; color: red;">
              @if($userRole == 1)
              Admin
              @elseif($userRole == 2)
              User
              @endif
            </label>
            <div class="box-body">
              <table id="example2" class="table table-bordered table-hover">
                <thead>
                <tr>
                  <th>#</th>
                  <th>Name</th>  
                  <th>View</th>   
                  <th>Edit</th> 
                  <th>Create</th> 
                  <th>Delete</th>      
                </tr>
                </thead>
                <tbody>
                    <?php $i = -2; ?>
                @foreach($priview as $priview)
                    <?php $i++ ?>
                  @if ($priview->name != 'Color' && $priview->name != 'Category')
                    <tr>
                      <td>{{ $i }}</td>
                        <td>
                          {{ $priview->name }}
                        </td> 
                        <td>
                        <?php
                        if( $priview->index == 1 )
                        {
                          ?>
                          <input type="checkbox" name="{{ $priview->name }}view" value="1" checked/>
                        <?php
                        }
                        else
                        {
                        ?>
                          <input type="checkbox" name="{{ $priview->name }}view" value="1" />
                        <?php
                        }
                        ?>
                        </td>

                        <td>
                        <?php
                        if( $priview->edit == 1 )
                        {
                          ?>
                          <input type="checkbox" name="{{ $priview->name }}edit" value="1" checked/>
                        <?php
                        }
                        else
                        {
                        ?>
                          <input type="checkbox" name="{{ $priview->name }}edit" value="1" />
                        <?php
                        }
                        ?>
                        </td>

                        <td>
                        <?php
                        if( $priview->create == 1 )
                        {
                          ?>
                          <input type="checkbox" name="{{ $priview->name }}create" value="1" checked/>
                        <?php
                        }
                        else
                        {
                        ?>
                          <input type="checkbox" name="{{ $priview->name }}create" value="1" />
                        <?php
                        }
                        ?>
                        </td>

                        <td>
                        <?php
                        if( $priview->delete == 1 )
                        {
                          ?>
                          <input type="checkbox" name="{{ $priview->name }}delete" value="1" checked/>
                        <?php
                        }
                        else
                        {
                        ?>
                          <input type="checkbox" name="{{ $priview->name }}delete" value="1" />
                        <?php
                        }
                        ?>
                        </td>
                      
                      
                    </tr>
                  @endif
                @endforeach
                
                </tfoot>
              </table>
                          
            </div>

            <div class="box-footer">
              <button id='submit' type="submit" class="btn btn-primary">Save</button>
            </div>
          </form>


          </div>
          <!-- /.box -->


      </div>
    </div>


    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
    @include('footer')
  
    @include('rightside')
    
    <div class="control-sidebar-bg"></div>
  </div>
  <!-- ./wrapper -->

@endsection